image: gitlab/dind

services:
  - docker:18.09.7-dind

stages:
  - build

build backend:
  stage: build
  tags:
    - docker
  image:
    name: gitlab/dind
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${DOCKER_TEAM}/inview-backend ./backend
    - docker push ${DOCKER_TEAM}/inview-backend
  only:
    changes:
      - backend/*

build frontend:
  stage: build
  tags:
    - docker
  image:
    name: gitlab/dind
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker build -t ${DOCKER_TEAM}/inview-frontend ./frontend
    - docker push ${DOCKER_TEAM}/inview-frontend   
  only:
    changes:
      - frontend/*
